#!/usr/bin/env bash

# "exit mode" on error
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL="${BASEDIR}/${DOTBOT_DIR}/bin/dotbot"

# sync & update dotbot
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# install with params
"${INSTALL}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
